version: "3.8"

services:
  postgres:
    image: postgres:9.6
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - ./db/postgres:/var/lib/postgresql/data

  webserver:
    build: .
    restart: always
    entrypoint: ./scripts/webserver-entrypoint.sh
    depends_on:
      - postgres 
    env_file:
      - .env 
    ports:
      - '8080:8080'
    volumes:
      - ./scripts:/usr/local/airflow/scripts

  scheduler:
    build: .
    restart: always
    entrypoint: ./scripts/scheduler-entrypoint.sh
    depends_on:
      - postgres
      - webserver
    env_file:
      - .env
    ports:
      - '8793:8793'
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./scripts:/usr/local/airflow/scripts
      - ./data:/usr/local/airflow/data
      - /var/run/docker.sock:/var/run/docker.sock